apiVersion: v1
kind: Pod
metadata:
  name: diguage-manual
spec:
  containers:
    - name: diguage-kubia
      image: diguage/kubia
      ports:
        - containerPort: 8080
          protocol: TCP
      resources:
        limits:
          cpu: "500m"
        requests:
          cpu: "500m"